### ISSUE TITLE
The in kernel rt88 driver fails for rtl8812au usb adapter, rtw88-0.6 fails to build on 6.17.x and 6.17.x kernels

### ISSUE THREAD

**Issue by TNWesTex** [lwfinger/rtw88#393]
~]# lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 058f:6335 Alcor Micro Corp. SD/MMC Card Reader
Bus 001 Device 003: ID 0bda:b812 Realtek Semiconductor Corp. RTL88x2bu [AC1200 Techkey]
Bus 001 Device 004: ID 0451:8142 Texas Instruments, Inc. TUSB8041 4-Port Hub
Bus 001 Device 005: ID 0bda:8812 Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 8087:8002 Intel Corp. 8 channel internal hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 0451:8140 Texas Instruments, Inc. TUSB8041 4-Port Hub
Bus 003 Device 003: ID 0781:5581 SanDisk Corp. Ultra
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 002: ID 8087:800a Intel Corp. Hub

tx.c: In function ‘rtw_tx_report_purge_timer’:
tx.c:202:34: error: implicit declaration of function ‘from_timer’; did you mean ‘mod_timer’? [-Wimplicit-function-declaration]
  202 |         struct rtw_dev *rtwdev = from_timer(rtwdev, t, tx_report.purge_timer);
      |                                  ^~~~~~~~~~
      |                                  mod_timer
tx.c:202:56: error: ‘tx_report’ undeclared (first use in this function); did you mean ‘rtw_tx_report’?
  202 |         struct rtw_dev *rtwdev = from_timer(rtwdev, t, tx_report.purge_timer);
      |                                                        ^~~~~~~~~
      |                                                        rtw_tx_report
tx.c:202:56: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [/usr/src/kernels/6.16.7-200.fc42.x86_64/scripts/Makefile.build:287: tx.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [/usr/src/kernels/6.16.7-200.fc42.x86_64/Makefile:2033: .] Error 2
make[2]: *** [/usr/src/kernels/6.16.7-200.fc42.x86_64/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/rtw88/0.6/build'
~]# lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 058f:6335 Alcor Micro Corp. SD/MMC Card Reader
Bus 001 Device 003: ID 0bda:b812 Realtek Semiconductor Corp. RTL88x2bu [AC1200 Techkey]
Bus 001 Device 004: ID 0451:8142 Texas Instruments, Inc. TUSB8041 4-Port Hub
Bus 001 Device 005: ID 0bda:8812 Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 8087:8002 Intel Corp. 8 channel internal hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 0451:8140 Texas Instruments, Inc. TUSB8041 4-Port Hub
Bus 003 Device 003: ID 0781:5581 SanDisk Corp. Ultra
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 002: ID 8087:800a Intel Corp. Hub

make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.16.7-200.fc42.x86_64'
make: *** [Makefile:191: all] Error 2

With the in kernel rt88 driver while booting the following sequence is noted during boot
rtw88_8812au 1-14:1.0: Firmware version 52.14.8, H2C version 0
rtw88_8812au 1-14:1.0: failed to validate firmware
rtw88_8812au 1-14:1.0: failed to download firmware
rtw88_8812au 1-14:1.0: failed to setup chip efuse info
rtw88_8812au 1-14:1.0: failed to setup chip Information
rtw88_8812au 1-14:1.0: probe with driver rtw88_0812au failed with error -22
usbcore: registered new interface driver rtw88_8812au

Th adapter is not seen when the system starts. The RTL88x2bu based wifi adapter works with the in kernel driver
 ~]# inxi
CPU: quad core Intel Xeon E5-1630 v4 (-MT MCP-) speed: 1825 MHz
Kernel: 6.16.5-200.fc42.x86_64 x86_64 Up: 3h 22m Mem: 3.37/15.51 GiB (21.7%)
Storage: 3.72 TiB (4.7% used) Procs: 361 Shell: Bash inxi: 3.3.39

**Comment by morrownr** [comment]
Hi @TNWesTex 

Have you tested with the released kernel 6.17?

**Comment by morrownr** [comment]
I have a couple of reports that are similar to this in the out-of-kernel drivers that I support. I'll look at fixing them and then try to figure out what needs to be done here. This is most likely an API change that was not detected.

**Comment by morrownr** [comment]
Status?

**Comment by act1tube** [comment]
I encountered the same problem when I installed the driver on the host device (#399 ). After uninstalling the driver from the host, I was able to re-establish the connection on the VM
