### ISSUE TITLE
Build fails on AlmaLinux 9.6 with 5.14.0-570.62.1.el9_6.x86_64

### ISSUE THREAD

**Issue by rriemann** [lwfinger/rtw88#409]
Dears,

I have a fresh AlmaLinux 9.6 PC.

`sudo dnf install kernel-devel git dkms`

`cd rtw88 && sudo dkms install $PWD`

This leads to the following error: 

~~~
Deprecated feature: CLEAN (/usr/src/rtw88-0.6/dkms.conf)
Creating symlink /var/lib/dkms/rtw88/0.6/source -> /usr/src/rtw88-0.6

Sign command: /lib/modules/5.14.0-570.62.1.el9_6.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Certificate or key are missing, generating self signed certificate for MOK...

Building module(s)...(bad exit status: 2)
Failed command:
KVER=5.14.0-570.62.1.el9_6.x86_64 'make' all

Error! Bad return status for module build on kernel: 5.14.0-570.62.1.el9_6.x86_64 (x86_64)
Consult /var/lib/dkms/rtw88/0.6/build/make.log for more information.
~~~

[make.log](https://github.com/user-attachments/files/23509490/make.log)

First part of this log file:

~~~
DKMS (dkms-3.3.0) make.log for rtw88/0.6 for kernel 5.14.0-570.62.1.el9_6.x86_64 (x86_64)
Wed 12 Nov 21:20:38 CET 2025

Building module(s)
# command: KVER=5.14.0-570.62.1.el9_6.x86_64 'make' all
make -j11 -C /lib/modules/5.14.0-570.62.1.el9_6.x86_64/build M=$PWD modules
make[1]: Entering directory '/usr/src/kernels/5.14.0-570.62.1.el9_6.x86_64'
  CC [M]  /var/lib/dkms/rtw88/0.6/build/main.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/led.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/mac80211.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/util.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/debug.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/tx.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/rx.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/mac.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/phy.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/coex.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/efuse.o
In file included from /var/lib/dkms/rtw88/0.6/build/mac80211.c:5:
/var/lib/dkms/rtw88/0.6/build/main.h:69:1: error: redefinition of ‘cfg80211_ssid_eq’
   69 | cfg80211_ssid_eq(struct cfg80211_ssid *a, struct cfg80211_ssid *b)
      | ^~~~~~~~~~~~~~~~
In file included from ./include/net/mac80211.h:22,
                 from /var/lib/dkms/rtw88/0.6/build/main.h:12,
                 from /var/lib/dkms/rtw88/0.6/build/mac80211.c:5:
./include/net/cfg80211.h:7384:1: note: previous definition of ‘cfg80211_ssid_eq’ with type ‘bool(struct cfg80211_ssid *, struct cfg80211_ssid *)’ {aka ‘_Bool(struct cfg80211_ssid *, struct cfg80211_ssid *)’}
 7384 | cfg80211_ssid_eq(struct cfg80211_ssid *a, struct cfg80211_ssid *b)
      | ^~~~~~~~~~~~~~~~
/var/lib/dkms/rtw88/0.6/build/mac80211.c: In function ‘rtw_ops_bss_info_changed’:
/var/lib/dkms/rtw88/0.6/build/mac80211.c:406:25: error: ‘struct ieee80211_bss_conf’ has no member named ‘assoc’
  406 |                 if (conf->assoc) {
      |                         ^~
/var/lib/dkms/rtw88/0.6/build/mac80211.c:415:66: error: ‘struct ieee80211_bss_conf’ has no member named ‘assoc’
  415 |                         rtw_coex_media_status_notify(rtwdev, conf->assoc);
      |                                                                  ^~
/var/lib/dkms/rtw88/0.6/build/mac80211.c: At top level:
/var/lib/dkms/rtw88/0.6/build/mac80211.c:1040:35: error: initialization of ‘void (*)(struct ieee80211_hw *, bool)’ {aka ‘void (*)(struct ieee80211_hw *, _Bool)’} from incompatible pointer type ‘void (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
 1040 |         .stop                   = rtw_ops_stop,
      |                                   ^~~~~~~~~~~~
/var/lib/dkms/rtw88/0.6/build/mac80211.c:1040:35: note: (near initialization for ‘rtw_ops.stop’)
/var/lib/dkms/rtw88/0.6/build/mac80211.c:1046:35: error: initialization of ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, u64)’ {aka ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, long long unsigned int)’} from incompatible pointer type ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, u32)’ {aka ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, unsigned int)’} [-Werror=incompatible-pointer-types]
 1046 |         .bss_info_changed       = rtw_ops_bss_info_changed,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~
~~~

What's wrong?
