### ISSUE TITLE
RTL8821AU fails to compile on Alma Linux 10.1 with kernel 6.12

### ISSUE THREAD

**Issue by jorgeprediger** [lwfinger/rtw88#421]
The change from the `sta_rc_update` callback to `link_sta_rc_update` is theoretically implemented starting with kernel 6.12. However, the source code at [https://github.com/lwfinger/rtw88/blob/master/mac80211.c](https://github.com/lwfinger/rtw88/blob/master/mac80211.c) refers to kernel version 6.13.

Driver RTL8821AU fails to compile on Alma Linux 10.1 with kernel 6.12

```Building module(s)
# command: KVER=6.12.0-124.20.1.el10_1.x86_64 'make' all
make -j7 -C /lib/modules/6.12.0-124.20.1.el10_1.x86_64/build M=$PWD modules
make[1]: se entra en el directorio '/usr/src/kernels/6.12.0-124.20.1.el10_1.x86_64'
  CC [M]  /var/lib/dkms/rtw88/0.6/build/main.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/led.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/mac80211.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/util.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/debug.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/tx.o
  CC [M]  /var/lib/dkms/rtw88/0.6/build/rx.o
/var/lib/dkms/rtw88/0.6/build/mac80211.c:1071:10: error: ‘const struct ieee80211_ops’ no tiene un miembro llamado ‘sta_rc_update’; ¿quiso decir ‘link_sta_rc_update’?
 1071 |         .sta_rc_update          = rtw_ops_sta_rc_update,
      |          ^~~~~~~~~~~~~
      |          link_sta_rc_update
/var/lib/dkms/rtw88/0.6/build/mac80211.c:1071:35: error: inicialización de ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct cfg80211_sched_scan_request *, struct ieee80211_scan_ies *)’ desde un tipo de puntero ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_sta *, u32)’ {también conocido como ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_sta *, unsigned int)’} incompatible [-Wincompatible-pointer-types]
 1071 |         .sta_rc_update          = rtw_ops_sta_rc_update,
      |                                   ^~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/rtw88/0.6/build/mac80211.c:1071:35: nota: (cerca de la inicialización de ‘rtw_ops.sched_scan_start’)
make[3]: *** [scripts/Makefile.build:229: /var/lib/dkms/rtw88/0.6/build/mac80211.o] Error 1
make[3]: *** Se espera a que terminen otras tareas....
make[2]: *** [/usr/src/kernels/6.12.0-124.20.1.el10_1.x86_64/Makefile:1994: /var/lib/dkms/rtw88/0.6/build] Error 2
make[1]: *** [Makefile:242: __sub-make] Error 2
make[1]: se sale del directorio '/usr/src/kernels/6.12.0-124.20.1.el10_1.x86_64'
make: *** [Makefile:183: all] Error 2

# exit code: 2
# elapsed time: 00:00:02
```

**Comment by jorgeprediger** [comment]
We replaced all references to "KERNEL_VERSION(6, 13, 0)" with "KERNEL_VERSION(6, 12, 0)" and the compilation was successful and it seems to work correctly, but I'm not entirely sure if that change is the correct one.

**Comment by dubhater** [comment]
According to Github, sta_rc_update was renamed in kernel 6.13: https://github.com/torvalds/linux/commit/88b67e91e2928c3311f3658d1270b40708b0de00

Alma Linux and some other Red Hat derivatives (not Fedora) use modified kernels, which causes problems with external drivers. They backport API changes, like this one.
